
name: Building AMI on Merge

env:
  ARTIFACT_NAME: csye6225-webapp-${{github.sha}}.zip
  CODEDEPLOY_APPLICATION_NAME: webapp
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: webapp
  AWS_REGION: us-east-1
on:
  push:
    branches: [ main ]
    paths:
      - "source/startup.sh"
      - "aws-linux-ami.pkr.hcl"
      - "package.json"
      - "amazon-cloudwatch-agent.json"
      - "application_boot.service"


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Setting up Hashicorp Packer
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.7.10

    - name: AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_GH_DEV_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_GH_DEV_SECRET_ACCESS_KEY }}
        aws-region:  ${{ env.AWS_REGION }}

    - name: Setting packer logs to Verbose
      run: export PACKER_LOG=1

    - name: Installing packer provisioners
      run: packer init aws-linux-ami.pkr.hcl

    - name: Running Packer template validation
      run: packer validate aws-linux-ami.pkr.hcl

    - name: Printing the contents of Directory before Packer build
      run: ls -l

        
    - name: Building Packer Template
      run: packer build aws-linux-ami.pkr.hcl


    - name: Printing the contents of Directory
      run: ls -al

