
name: Building AMI on Merge

env:
  AWS_REGION: us-east-1
on:
  push:
    branches: [ main,assignment10 ]
    paths:
      - aws-linux-ami.pkr.hcl
      - package.json
      - startup.sh
      - application_boot.service
      - amazon-cloudwatch-agent.json
      - node_startup.sh


jobs:
  ami_creation_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Hashicorp Packer
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.7.10

    - name: AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_GH_DEV_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_GH_DEV_SECRET_ACCESS_KEY }}
        aws-region:  ${{ env.AWS_REGION }}

    - name: Setting packer logs to Verbose
      run: export PACKER_LOG=1

    - name: Installing packer provisioners
      run: packer init aws-linux-ami.pkr.hcl


    - name: Printing the contents of Directory
      run: ls -l


    - name: Building Packer Template
      run: packer build aws-linux-ami.pkr.hcl

    - name: Printing the contents of Directory after building
      run: ls -l